workflows:
  ios_unsigned:
    name: iOS (unsigned) - SAVO
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: |
          cd apps/mobile
          flutter --version
          flutter pub get
      - name: Build iOS (no codesign)
        script: |
          cd apps/mobile
          flutter build ios --release --no-codesign
    artifacts:
      - apps/mobile/build/ios/iphoneos/*.app
      - apps/mobile/build/ios/archive/*.xcarchive
      - apps/mobile/flutter_*.log

  ios_ipa:
    name: iOS IPA (signed) - SAVO
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: |
          cd apps/mobile
          flutter --version
          flutter pub get
      - name: Build IPA
        script: |
          cd apps/mobile
          flutter build ipa --release
    artifacts:
      - apps/mobile/build/ios/ipa/*.ipa
      - apps/mobile/flutter_*.log
