"""Cuisine metadata.

Kept intentionally lightweight but extended beyond a small MVP set so the planner
can enforce stronger cultural/region selection (e.g., India sub-regions, SE Asia,
Europe).
"""

CUISINE_METADATA = {
    "italian": {
        "name": "Italian",
        "daily_structure": ["Antipasto", "Primo (Pasta/Risotto)", "Secondo (Main)", "Contorno (Side)"],
        "party_structure": ["Antipasti", "Primi", "Secondi", "Contorni", "Dolci"],
        "characteristics": ["pasta", "tomato", "olive oil", "basil", "parmesan"],
        "region": "Europe",
        "countries": ["IT"],
        "country_names": ["italy"],
        "languages": ["it", "en"],
        "language_names": ["italian"],
        "aliases": [],
        "keywords": ["mediterranean", "italia"],
    },
    "mexican": {
        "name": "Mexican",
        "daily_structure": ["Appetizer", "Main Course", "Side", "Dessert"],
        "party_structure": ["Antojitos", "Platos Fuertes", "Acompañamientos", "Postres"],
        "characteristics": ["tortilla", "beans", "corn", "chili", "cilantro"],
        "region": "North America",
        "countries": ["MX"],
        "country_names": ["mexico"],
        "languages": ["es", "en"],
        "language_names": ["spanish"],
        "aliases": [],
        "keywords": ["antojitos", "tacos", "salsa"],
    },
    "chinese": {
        "name": "Chinese",
        "daily_structure": ["Appetizer", "Main Dish", "Rice/Noodles", "Soup"],
        "party_structure": ["Cold Dishes", "Hot Dishes", "Rice/Noodles", "Soup", "Dessert"],
        "characteristics": ["soy sauce", "ginger", "garlic", "rice", "wok-fried"],
        "region": "East Asia",
        "countries": ["CN"],
        "country_names": ["china"],
        "languages": ["zh", "en"],
        "language_names": ["chinese", "mandarin", "cantonese"],
        "aliases": ["zhongguo", "hong kong"],
        "keywords": ["dim sum", "noodles", "stir-fry"],
    },
    "indian": {
        "name": "Indian",
        "daily_structure": ["Starter", "Main Curry", "Bread/Rice", "Side"],
        "party_structure": ["Appetizers", "Curries", "Breads", "Rice Dishes", "Desserts"],
        "characteristics": ["curry", "spices", "naan", "rice", "lentils"],
        "region": "South Asia",
        "countries": ["IN"],
        "country_names": ["india"],
        "languages": ["hi", "en"],
        "language_names": ["hindi", "english"],
        "aliases": [],
        "keywords": ["south asia", "desi"],
    },
    "punjabi": {
        "name": "Punjabi (North India)",
        "daily_structure": ["Starter", "Main Curry", "Bread", "Side"],
        "party_structure": ["Starters", "Curries", "Breads", "Rice", "Desserts"],
        "characteristics": ["tandoor", "makhani", "ghee", "paneer", "wheat"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Punjab",
        "languages": ["pa", "hi", "en"],
        "country_names": ["india"],
        "language_names": ["punjabi", "hindi", "english"],
        "aliases": [],
        "keywords": ["north india", "tandoor"],
    },
    "gujarati": {
        "name": "Gujarati (West India)",
        "daily_structure": ["Snack", "Sabzi", "Dal", "Rice/Roti"],
        "party_structure": ["Farsan", "Sabzi", "Dal", "Rice", "Desserts"],
        "characteristics": ["sweet-sour", "farsan", "lentils", "jaggery", "mustard seeds"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Gujarat",
        "languages": ["gu", "hi", "en"],
        "country_names": ["india"],
        "language_names": ["gujarati", "hindi", "english"],
        "aliases": [],
        "keywords": ["west india"],
    },
    "bengali": {
        "name": "Bengali (East India)",
        "daily_structure": ["Starter", "Fish/Protein", "Rice", "Dal"],
        "party_structure": ["Starters", "Mains", "Rice", "Dal", "Sweets"],
        "characteristics": ["mustard", "fish", "panch phoron", "rice", "mishti"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: West Bengal",
        "languages": ["bn", "en"],
        "country_names": ["india"],
        "language_names": ["bengali", "english"],
        "aliases": [],
        "keywords": ["east india"],
    },
    "hyderabadi": {
        "name": "Hyderabadi (Deccan)",
        "daily_structure": ["Starter", "Main", "Rice", "Side"],
        "party_structure": ["Starters", "Rice Dishes", "Curries", "Breads", "Desserts"],
        "characteristics": ["biryani", "mint", "fried onions", "yogurt", "spices"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Telangana",
        "languages": ["te", "ur", "hi", "en"],
        "country_names": ["india"],
        "language_names": ["telugu", "urdu", "hindi", "english"],
        "aliases": [],
        "keywords": ["deccan"],
    },
    "tamil": {
        "name": "Tamil (South India)",
        "daily_structure": ["Chutney", "Sambar", "Rice", "Poriyal"],
        "party_structure": ["Tiffin", "Kuzhambu/Sambar", "Rice", "Poriyal", "Payasam"],
        "characteristics": ["tamarind", "curry leaves", "lentils", "coconut", "rice"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Tamil Nadu",
        "languages": ["ta", "en"],
        "country_names": ["india"],
        "language_names": ["tamil", "english"],
        "aliases": [],
        "keywords": ["south india"],
    },
    "kerala": {
        "name": "Kerala (South India)",
        "daily_structure": ["Thoran", "Curry", "Rice", "Side"],
        "party_structure": ["Snacks", "Curries", "Rice", "Sides", "Desserts"],
        "characteristics": ["coconut", "curry leaves", "seafood", "black pepper", "tamarind"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Kerala",
        "languages": ["ml", "en"],
        "country_names": ["india"],
        "language_names": ["malayalam", "english"],
        "aliases": [],
        "keywords": ["south india"],
    },
    "andhra": {
        "name": "Andhra (South India)",
        "daily_structure": ["Chutney", "Dal", "Rice", "Fry"],
        "party_structure": ["Starters", "Curries", "Rice", "Sides", "Sweets"],
        "characteristics": ["chili", "tamarind", "gongura", "lentils", "rice"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Andhra Pradesh",
        "languages": ["te", "en"],
        "country_names": ["india"],
        "language_names": ["telugu", "english"],
        "aliases": [],
        "keywords": ["south india"],
    },
    "kannada": {
        "name": "Kannada (Karnataka)",
        "daily_structure": ["Chutney/Palya", "Sambar/Gravy", "Rice", "Side"],
        "party_structure": ["Tiffin", "Rice Dishes", "Curries", "Sides", "Payasa"],
        "characteristics": ["coconut", "curry leaves", "lentils", "tamarind", "rice"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Karnataka",
        "country_names": ["india"],
        "languages": ["kn", "en"],
        "language_names": ["kannada", "english"],
        "aliases": ["karnataka", "kanada"],
        "keywords": ["south india", "udupi", "mangalorean", "kanada"],
    },
    "marathi": {
        "name": "Marathi (Maharashtrian)",
        "daily_structure": ["Snack", "Main", "Rice/Bhakri", "Side"],
        "party_structure": ["Snacks", "Mains", "Rice/Breads", "Sides", "Sweets"],
        "characteristics": ["kokum", "peanuts", "sesame", "spices", "rice"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Maharashtra",
        "country_names": ["india"],
        "languages": ["mr", "hi", "en"],
        "language_names": ["marathi", "hindi", "english"],
        "aliases": ["maharashtrian"],
        "keywords": ["west india", "konkan"],
    },
    "rajasthani": {
        "name": "Rajasthani (Northwest India)",
        "daily_structure": ["Starter", "Main", "Bread", "Side"],
        "party_structure": ["Starters", "Mains", "Breads", "Rice", "Sweets"],
        "characteristics": ["ghee", "millets", "lentils", "spices", "pickle"],
        "region": "South Asia",
        "countries": ["IN"],
        "subregion": "India: Rajasthan",
        "country_names": ["india"],
        "languages": ["hi", "en"],
        "language_names": ["hindi", "english"],
        "aliases": [],
        "keywords": ["north india", "thali"],
    },
    "japanese": {
        "name": "Japanese",
        "daily_structure": ["Starter", "Main", "Rice", "Soup"],
        "party_structure": ["Appetizers", "Sashimi/Sushi", "Grilled", "Noodles", "Dessert"],
        "characteristics": ["soy", "miso", "rice", "fish", "seaweed"],
        "region": "East Asia",
        "countries": ["JP"],
        "country_names": ["japan"],
        "languages": ["ja", "en"],
        "language_names": ["japanese"],
        "aliases": [],
        "keywords": ["washoku", "sushi", "ramen"],
    },
    "french": {
        "name": "French",
        "daily_structure": ["Entrée", "Plat Principal", "Fromage", "Dessert"],
        "party_structure": ["Hors d'œuvres", "Entrées", "Plats", "Fromages", "Desserts"],
        "characteristics": ["butter", "wine", "cream", "herbs", "pastry"],
        "region": "Europe",
        "countries": ["FR"],
        "country_names": ["france"],
        "languages": ["fr", "en"],
        "language_names": ["french", "english"],
        "aliases": [],
        "keywords": [],
    },
    "mediterranean": {
        "name": "Mediterranean",
        "daily_structure": ["Mezze", "Main", "Salad", "Side"],
        "party_structure": ["Mezze Platter", "Mains", "Salads", "Sides", "Sweets"],
        "characteristics": ["olive oil", "lemon", "garlic", "chickpeas", "feta"],
        "region": "Mediterranean",
        "countries": ["ES", "FR", "IT", "GR", "TR", "LB", "IL", "EG", "MA", "TN"],
        "country_names": ["spain", "france", "italy", "greece", "turkey", "lebanon", "israel", "egypt", "morocco", "tunisia"],
        "languages": ["en", "es", "fr", "it", "el", "ar", "tr"],
        "language_names": ["arabic", "turkish", "greek", "italian", "spanish", "french"],
        "aliases": ["med"],
        "keywords": ["mezze", "seafood", "olive"],
    },
    "thai": {
        "name": "Thai",
        "daily_structure": ["Appetizer", "Curry/Stir-fry", "Rice", "Soup"],
        "party_structure": ["Appetizers", "Salads", "Curries", "Stir-fries", "Desserts"],
        "characteristics": ["fish sauce", "lime", "chili", "coconut", "lemongrass"],
        "region": "Southeast Asia",
        "countries": ["TH"],
        "country_names": ["thailand"],
        "languages": ["th", "en"],
        "language_names": ["thai", "english"],
        "aliases": [],
        "keywords": [],
    },
    "vietnamese": {
        "name": "Vietnamese",
        "daily_structure": ["Fresh starter", "Main", "Rice/Noodles", "Soup"],
        "party_structure": ["Starters", "Mains", "Noodles", "Salads", "Desserts"],
        "characteristics": ["fish sauce", "lime", "herbs", "rice noodles", "pickles"],
        "region": "Southeast Asia",
        "countries": ["VN"],
        "country_names": ["vietnam"],
        "languages": ["vi", "en"],
        "language_names": ["vietnamese", "english"],
        "aliases": [],
        "keywords": [],
    },
    "indonesian": {
        "name": "Indonesian",
        "daily_structure": ["Sambal", "Main", "Rice", "Side"],
        "party_structure": ["Starters", "Mains", "Rice", "Sides", "Sweets"],
        "characteristics": ["sambal", "soy sauce", "coconut", "peanuts", "lemongrass"],
        "region": "Southeast Asia",
        "countries": ["ID"],
        "country_names": ["indonesia"],
        "languages": ["id", "en"],
        "language_names": ["indonesian", "bahasa", "english"],
        "aliases": [],
        "keywords": [],
    },
    "malaysian": {
        "name": "Malaysian",
        "daily_structure": ["Starter", "Curry", "Rice/Noodles", "Side"],
        "party_structure": ["Starters", "Mains", "Rice/Noodles", "Sides", "Desserts"],
        "characteristics": ["coconut", "chili", "shrimp paste", "lime", "spices"],
        "region": "Southeast Asia",
        "countries": ["MY"],
        "country_names": ["malaysia"],
        "languages": ["ms", "en"],
        "language_names": ["malay", "english"],
        "aliases": [],
        "keywords": [],
    },
    "filipino": {
        "name": "Filipino",
        "daily_structure": ["Starter", "Main", "Rice", "Side"],
        "party_structure": ["Starters", "Mains", "Rice", "Sides", "Desserts"],
        "characteristics": ["vinegar", "soy sauce", "garlic", "coconut", "stew"],
        "region": "Southeast Asia",
        "countries": ["PH"],
        "country_names": ["philippines"],
        "languages": ["tl", "en"],
        "language_names": ["tagalog", "filipino", "english"],
        "aliases": [],
        "keywords": [],
    },
    "singaporean": {
        "name": "Singaporean",
        "daily_structure": ["Starter", "Noodles/Rice", "Main", "Side"],
        "party_structure": ["Starters", "Noodles", "Mains", "Sides", "Desserts"],
        "characteristics": ["hawker", "chili", "soy", "seafood", "noodles"],
        "region": "Southeast Asia",
        "countries": ["SG"],
        "country_names": ["singapore"],
        "languages": ["en", "zh", "ms", "ta"],
        "language_names": ["english", "chinese", "mandarin", "malay", "tamil"],
        "aliases": [],
        "keywords": [],
    },
    "spanish": {
        "name": "Spanish",
        "daily_structure": ["Tapas", "Main", "Side", "Dessert"],
        "party_structure": ["Tapas", "Mains", "Sides", "Desserts"],
        "characteristics": ["olive oil", "paprika", "garlic", "seafood", "rice"],
        "region": "Europe",
        "countries": ["ES"],
        "country_names": ["spain"],
        "languages": ["es", "en"],
        "language_names": ["spanish", "english"],
        "aliases": [],
        "keywords": [],
    },
    "greek": {
        "name": "Greek",
        "daily_structure": ["Meze", "Main", "Salad", "Side"],
        "party_structure": ["Meze", "Mains", "Salads", "Sides", "Sweets"],
        "characteristics": ["olive oil", "lemon", "oregano", "feta", "yogurt"],
        "region": "Europe",
        "countries": ["GR"],
        "country_names": ["greece"],
        "languages": ["el", "en"],
        "language_names": ["greek", "english"],
        "aliases": [],
        "keywords": [],
    },
    "portuguese": {
        "name": "Portuguese",
        "daily_structure": ["Starter", "Main", "Side", "Dessert"],
        "party_structure": ["Starters", "Mains", "Sides", "Desserts"],
        "characteristics": ["olive oil", "garlic", "paprika", "seafood", "stew"],
        "region": "Europe",
        "countries": ["PT"],
        "country_names": ["portugal"],
        "languages": ["pt", "en"],
        "language_names": ["portuguese", "english"],
        "aliases": [],
        "keywords": [],
    },
    "british": {
        "name": "British",
        "daily_structure": ["Starter", "Main", "Side", "Dessert"],
        "party_structure": ["Starters", "Mains", "Sides", "Desserts"],
        "characteristics": ["roast", "gravy", "potatoes", "pies", "comfort food"],
        "region": "Europe",
        "countries": ["GB"],
        "country_names": ["united kingdom", "uk", "britain", "england", "scotland", "wales"],
        "languages": ["en"],
        "language_names": ["english"],
        "aliases": [],
        "keywords": ["roast dinner", "pies", "fish and chips"],
    },
    "german": {
        "name": "German",
        "daily_structure": ["Starter", "Main", "Side", "Dessert"],
        "party_structure": ["Starters", "Mains", "Sides", "Desserts"],
        "characteristics": ["sausages", "cabbage", "potatoes", "mustard", "bread"],
        "region": "Europe",
        "countries": ["DE"],
        "country_names": ["germany"],
        "languages": ["de", "en"],
        "language_names": ["german", "english"],
        "aliases": [],
        "keywords": ["bratwurst", "sauerkraut", "pretzel"],
    },
    "polish": {
        "name": "Polish",
        "daily_structure": ["Soup", "Main", "Side", "Dessert"],
        "party_structure": ["Soups", "Mains", "Sides", "Desserts"],
        "characteristics": ["dumplings", "cabbage", "mushrooms", "potatoes", "sour cream"],
        "region": "Europe",
        "countries": ["PL"],
        "country_names": ["poland"],
        "languages": ["pl", "en"],
        "language_names": ["polish", "english"],
        "aliases": [],
        "keywords": ["pierogi", "bigos", "borscht"],
    },
    "russian": {
        "name": "Russian",
        "daily_structure": ["Soup", "Main", "Side", "Dessert"],
        "party_structure": ["Zakuski", "Soups", "Mains", "Desserts"],
        "characteristics": ["dill", "sour cream", "beets", "potatoes", "cabbage"],
        "region": "Europe",
        "countries": ["RU"],
        "country_names": ["russia"],
        "languages": ["ru", "en"],
        "language_names": ["russian", "english"],
        "aliases": [],
        "keywords": ["borscht", "pelmeni", "blini"],
    },
    "scandinavian": {
        "name": "Scandinavian",
        "daily_structure": ["Starter", "Main", "Side", "Dessert"],
        "party_structure": ["Smörgåsbord", "Mains", "Sides", "Desserts"],
        "characteristics": ["fish", "potatoes", "dill", "rye", "pickled"],
        "region": "Europe",
        "countries": ["SE", "NO", "DK", "FI", "IS"],
        "country_names": ["sweden", "norway", "denmark", "finland", "iceland"],
        "languages": ["sv", "no", "da", "fi", "is", "en"],
        "language_names": ["swedish", "norwegian", "danish", "finnish", "icelandic", "english"],
        "aliases": ["nordic"],
        "keywords": ["smorgasbord", "gravlax", "meatballs"],
    },
    "american": {
        "name": "American",
        "daily_structure": ["Starter", "Main Course", "Side Dish", "Dessert"],
        "party_structure": ["Appetizers", "Mains", "Sides", "Salads", "Desserts"],
        "characteristics": ["grilled", "bbq", "burgers", "comfort food", "hearty"],
        "region": "North America",
        "countries": ["US"],
        "country_names": ["united states", "usa"],
        "languages": ["en"],
        "language_names": ["english"],
        "aliases": [],
        "keywords": ["barbecue", "bbq", "diner"],
    },
    "cajun": {
        "name": "Cajun",
        "daily_structure": ["Starter", "Main", "Rice/Side", "Dessert"],
        "party_structure": ["Starters", "Mains", "Rice/Side", "Desserts"],
        "characteristics": ["holy trinity", "roux", "andouille", "cayenne", "gumbo"],
        "region": "North America",
        "subregion": "US: Louisiana",
        "countries": ["US"],
        "country_names": ["united states", "usa"],
        "languages": ["en", "fr"],
        "language_names": ["english", "french"],
        "aliases": ["acadiana"],
        "keywords": ["bayou", "creole", "crawfish"],
    },
    "korean": {
        "name": "Korean",
        "daily_structure": ["Banchan", "Main", "Rice/Noodles", "Soup/Stew"],
        "party_structure": ["Banchan", "BBQ/Grilled", "Stews", "Noodles", "Dessert"],
        "characteristics": ["gochujang", "kimchi", "sesame", "soy", "garlic"],
        "region": "East Asia",
        "countries": ["KR"],
        "country_names": ["korea", "south korea"],
        "languages": ["ko", "en"],
        "language_names": ["korean"],
        "aliases": ["hanguk"],
        "keywords": ["banchan", "bulgogi", "bibimbap"],
    },
    "turkish": {
        "name": "Turkish",
        "daily_structure": ["Meze", "Main", "Rice/Bread", "Dessert"],
        "party_structure": ["Meze", "Grilled", "Mains", "Sides", "Sweets"],
        "characteristics": ["yogurt", "sumac", "lamb", "eggplant", "bulgur"],
        "region": "West Asia",
        "countries": ["TR"],
        "country_names": ["turkey"],
        "languages": ["tr", "en"],
        "language_names": ["turkish"],
        "aliases": ["turkiye"],
        "keywords": ["kebab", "meze", "pide"],
    },
    "lebanese": {
        "name": "Lebanese",
        "daily_structure": ["Mezze", "Main", "Salad", "Dessert"],
        "party_structure": ["Cold Mezze", "Hot Mezze", "Grilled Mains", "Salads", "Sweets"],
        "characteristics": ["tahini", "lemon", "garlic", "parsley", "olive oil"],
        "region": "West Asia",
        "countries": ["LB"],
        "country_names": ["lebanon"],
        "languages": ["ar", "fr", "en"],
        "language_names": ["arabic", "french"],
        "aliases": [],
        "keywords": ["mezze", "tabbouleh", "shawarma"],
    },
    "persian": {
        "name": "Persian (Iranian)",
        "daily_structure": ["Starter", "Khoresh (Stew)", "Rice", "Side"],
        "party_structure": ["Starters", "Rice Dishes", "Stews", "Grilled", "Desserts"],
        "characteristics": ["saffron", "rice", "herbs", "pomegranate", "yogurt"],
        "region": "West Asia",
        "countries": ["IR"],
        "country_names": ["iran"],
        "languages": ["fa", "en"],
        "language_names": ["persian", "farsi"],
        "aliases": ["iranian"],
        "keywords": ["chelow", "khoresh", "kebab"],
    },
    "moroccan": {
        "name": "Moroccan",
        "daily_structure": ["Salad", "Tagine", "Couscous", "Dessert"],
        "party_structure": ["Salads", "Tagines", "Couscous", "Sides", "Sweets"],
        "characteristics": ["ras el hanout", "preserved lemon", "olives", "couscous", "mint"],
        "region": "North Africa",
        "countries": ["MA"],
        "country_names": ["morocco"],
        "languages": ["ar", "fr", "en"],
        "language_names": ["arabic", "french"],
        "aliases": [],
        "keywords": ["tagine", "couscous", "harissa"],
    },
    "ethiopian": {
        "name": "Ethiopian",
        "daily_structure": ["Injera", "Wot (Stew)", "Vegetable Side", "Condiments"],
        "party_structure": ["Injera", "Wots", "Sides", "Salads", "Coffee/Tea"],
        "characteristics": ["berbere", "injera", "lentils", "spiced stew", "clarified butter"],
        "region": "East Africa",
        "countries": ["ET"],
        "country_names": ["ethiopia"],
        "languages": ["am", "en"],
        "language_names": ["amharic"],
        "aliases": [],
        "keywords": ["injera", "berbere", "wot"],
    },
    "nigerian": {
        "name": "Nigerian",
        "daily_structure": ["Soup/Stew", "Swallow/Starch", "Side", "Drink"],
        "party_structure": ["Starters", "Rice Dishes", "Soups", "Sides", "Desserts"],
        "characteristics": ["palm oil", "pepper", "yam", "plantain", "stew"],
        "region": "West Africa",
        "countries": ["NG"],
        "country_names": ["nigeria"],
        "languages": ["en"],
        "language_names": ["english"],
        "aliases": [],
        "keywords": ["jollof", "egusi", "suya"],
    },
    "brazilian": {
        "name": "Brazilian",
        "daily_structure": ["Starter", "Main", "Rice/Beans", "Dessert"],
        "party_structure": ["Petiscos", "Mains", "Sides", "Salads", "Desserts"],
        "characteristics": ["rice", "beans", "cassava", "lime", "grilled meats"],
        "region": "South America",
        "countries": ["BR"],
        "country_names": ["brazil"],
        "languages": ["pt", "en"],
        "language_names": ["portuguese"],
        "aliases": [],
        "keywords": ["feijoada", "churrasco", "moqueca"],
    },
    "peruvian": {
        "name": "Peruvian",
        "daily_structure": ["Starter", "Main", "Side", "Dessert"],
        "party_structure": ["Starters", "Mains", "Sides", "Salads", "Desserts"],
        "characteristics": ["aji", "lime", "potatoes", "corn", "seafood"],
        "region": "South America",
        "countries": ["PE"],
        "country_names": ["peru"],
        "languages": ["es", "en"],
        "language_names": ["spanish"],
        "aliases": [],
        "keywords": ["ceviche", "aji amarillo", "anticuchos"],
    },
    "caribbean": {
        "name": "Caribbean",
        "daily_structure": ["Starter", "Main", "Rice/Side", "Dessert"],
        "party_structure": ["Starters", "Mains", "Rice", "Sides", "Desserts"],
        "characteristics": ["allspice", "scotch bonnet", "coconut", "plantain", "rum"],
        "region": "Caribbean",
        "countries": ["JM", "TT", "BB", "HT", "DO", "PR", "CU"],
        "country_names": ["jamaica", "trinidad", "barbados", "haiti", "dominican", "puerto rico", "cuba"],
        "languages": ["en", "es", "fr"],
        "language_names": ["english", "spanish", "french"],
        "aliases": ["west indies"],
        "keywords": ["jerk", "plantain", "rice and peas"],
    },
    "jamaican": {
        "name": "Jamaican",
        "daily_structure": ["Starter", "Main", "Rice/Side", "Dessert"],
        "party_structure": ["Starters", "Mains", "Sides", "Desserts"],
        "characteristics": ["jerk", "allspice", "scotch bonnet", "thyme", "plantain"],
        "region": "Caribbean",
        "countries": ["JM"],
        "country_names": ["jamaica"],
        "languages": ["en"],
        "language_names": ["english"],
        "aliases": [],
        "keywords": ["jerk", "ackee", "rice and peas"],
    },
    "levantine": {
        "name": "Levantine",
        "daily_structure": ["Mezze", "Main", "Rice/Bread", "Dessert"],
        "party_structure": ["Cold Mezze", "Hot Mezze", "Grilled", "Rice Dishes", "Sweets"],
        "characteristics": ["olive oil", "lemon", "tahini", "parsley", "sumac"],
        "region": "West Asia",
        "countries": ["LB", "JO", "SY", "PS", "IL"],
        "country_names": ["lebanon", "jordan", "syria", "palestine", "israel"],
        "languages": ["ar", "he", "en"],
        "language_names": ["arabic", "hebrew", "english"],
        "aliases": [],
        "keywords": ["mezze", "falafel", "shawarma"],
    },
    "egyptian": {
        "name": "Egyptian",
        "daily_structure": ["Starter", "Main", "Rice/Bread", "Side"],
        "party_structure": ["Starters", "Mains", "Rice", "Sides", "Desserts"],
        "characteristics": ["fava beans", "garlic", "cumin", "pita", "herbs"],
        "region": "North Africa",
        "countries": ["EG"],
        "country_names": ["egypt"],
        "languages": ["ar", "en"],
        "language_names": ["arabic", "english"],
        "aliases": [],
        "keywords": ["koshari", "ful", "taameya"],
    },
    "iraqi": {
        "name": "Iraqi",
        "daily_structure": ["Starter", "Main", "Rice/Bread", "Side"],
        "party_structure": ["Starters", "Mains", "Rice", "Sides", "Sweets"],
        "characteristics": ["rice", "spices", "lamb", "herbs", "tahini"],
        "region": "West Asia",
        "countries": ["IQ"],
        "country_names": ["iraq"],
        "languages": ["ar", "ku", "en"],
        "language_names": ["arabic", "kurdish", "english"],
        "aliases": [],
        "keywords": ["dolma", "kebab", "stews"],
    },
    "arabian_gulf": {
        "name": "Arabian Gulf",
        "daily_structure": ["Starter", "Main", "Rice", "Side"],
        "party_structure": ["Starters", "Rice Dishes", "Mains", "Sides", "Sweets"],
        "characteristics": ["rice", "spices", "dates", "lamb", "cardamom"],
        "region": "Gulf",
        "countries": ["SA", "AE", "QA", "KW", "BH", "OM"],
        "country_names": ["saudi", "united arab emirates", "uae", "qatar", "kuwait", "bahrain", "oman"],
        "languages": ["ar", "en"],
        "language_names": ["arabic", "english"],
        "aliases": ["khaleeji"],
        "keywords": ["kabsa", "machboos", "harees"],
    },
    "middle_eastern": {
        "name": "Middle Eastern",
        "daily_structure": ["Mezze", "Main", "Rice/Bread", "Salad"],
        "party_structure": ["Cold Mezze", "Hot Mezze", "Grilled Mains", "Rice Dishes", "Sweets"],
        "characteristics": ["tahini", "cumin", "pita", "lamb", "yogurt"],
        "region": "Middle East",
        "countries": ["TR", "LB", "IL", "JO", "SY", "IQ", "IR", "SA", "AE", "EG"],
        "country_names": ["turkey", "lebanon", "israel", "jordan", "syria", "iraq", "iran", "saudi", "uae", "egypt"],
        "languages": ["ar", "fa", "he", "tr", "en"],
        "language_names": ["arabic", "persian", "hebrew", "turkish"],
        "aliases": ["mena"],
        "keywords": ["mezze", "shawarma", "kebab"],
    }
}


def get_all_cuisines():
    """Get all available cuisines with their structures"""
    cuisines = []
    for cuisine_id, data in CUISINE_METADATA.items():
        out = {
            "cuisine_id": cuisine_id,
            "name": data["name"],
            "daily_structure": data["daily_structure"],
            "party_structure": data["party_structure"],
            "characteristics": data["characteristics"],
        }

        # Optional metadata (safe for older clients).
        if data.get("region"):
            out["region"] = data.get("region")
        if data.get("subregion"):
            out["subregion"] = data.get("subregion")
        if isinstance(data.get("countries"), list):
            out["countries"] = data.get("countries")
        if isinstance(data.get("country_names"), list):
            out["country_names"] = data.get("country_names")
        if isinstance(data.get("languages"), list):
            out["languages"] = data.get("languages")
        if isinstance(data.get("language_names"), list):
            out["language_names"] = data.get("language_names")
        if isinstance(data.get("aliases"), list):
            out["aliases"] = data.get("aliases")
        if isinstance(data.get("keywords"), list):
            out["keywords"] = data.get("keywords")

        cuisines.append(out)

    return {"cuisines": cuisines}


def get_cuisine_by_id(cuisine_id: str):
    """Get specific cuisine metadata"""
    return CUISINE_METADATA.get(cuisine_id)
